"""Column domain models (task P1-DOM-02).

Represents a single column in a PostgreSQL table, including:

- Plain columns with an optional default expression
- Identity columns (``GENERATED ALWAYS AS IDENTITY`` / ``GENERATED BY DEFAULT AS IDENTITY``)
  together with their sequence options captured in :class:`IdentitySpec`.
- Generated (computed) stored columns (``GENERATED ALWAYS AS <expr> STORED``).

All models are pure domain: no IO, no async, no external drivers.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Self

from pydantic import BaseModel, ConfigDict, Field, model_validator


class GeneratedTiming(StrEnum):
    """Controls when an identity or generated column is populated."""

    ALWAYS = "always"
    BY_DEFAULT = "by_default"


class IdentitySpec(BaseModel):
    """Sequence options attached to an identity column.

    These correspond to the ``GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY``
    clause in ``CREATE TABLE`` / ``ALTER TABLE``.  All sequence options are
    optional; ``None`` means the Postgres default applies.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    generated: GeneratedTiming
    """Whether the identity is ``ALWAYS`` or ``BY DEFAULT``."""

    sequence_start: int | None = None
    """``START WITH`` value.  ``None`` → Postgres default (1)."""

    sequence_increment: int | None = None
    """``INCREMENT BY`` value.  ``None`` → Postgres default (1)."""

    sequence_min_value: int | None = None
    """``MINVALUE``.  ``None`` → Postgres default."""

    sequence_max_value: int | None = None
    """``MAXVALUE``.  ``None`` → Postgres default."""

    sequence_cache: int | None = None
    """``CACHE`` size.  ``None`` → Postgres default (1)."""

    sequence_cycle: bool = False
    """Whether the sequence cycles after reaching its limit."""

    @model_validator(mode="after")
    def _check_min_max(self) -> Self:
        if (
            self.sequence_min_value is not None
            and self.sequence_max_value is not None
            and self.sequence_min_value > self.sequence_max_value
        ):
            raise ValueError(
                f"sequence_min_value ({self.sequence_min_value}) must not exceed "
                f"sequence_max_value ({self.sequence_max_value})"
            )
        return self


class Column(BaseModel):
    """A column in a PostgreSQL table.

    Covers three column variants depending on which optional fields are set:

    1. **Plain column** — ``identity`` and ``generated_expression`` are both
       ``None``.
    2. **Identity column** — ``identity`` is an :class:`IdentitySpec`.
    3. **Generated stored column** — ``generated_expression`` holds the SQL
       expression and ``generated`` is ``ALWAYS`` (Postgres only supports
       ``ALWAYS`` for stored generated columns, not ``BY DEFAULT``).

    The ``position`` field matches ``pg_attribute.attnum`` (1-based), which is
    required to preserve column order inside a :class:`~pgschemadiff.domain.table.Table`.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    name: str = Field(min_length=1)
    """Column name (``pg_attribute.attname``)."""

    position: int = Field(ge=1)
    """1-based column ordinal (``pg_attribute.attnum``).  Must be ≥ 1."""

    data_type: str = Field(min_length=1)
    """Normalised PostgreSQL type string, e.g. ``"integer"``, ``"character varying(255)"``.

    The infrastructure layer is responsible for normalisation before constructing
    this model (see task P1-INFRA-06).
    """

    nullable: bool = True
    """``True`` if the column allows ``NULL`` (the default in Postgres)."""

    default_expr: str | None = None
    """SQL expression for the column default, verbatim from ``pg_get_expr``.

    ``None`` if no default is defined.  Must be ``None`` for identity or
    generated-stored columns because those carry their own generation spec.
    """

    collation: str | None = None
    """Collation name (e.g. ``"en_US.utf8"``).  ``None`` → database default."""

    identity: IdentitySpec | None = None
    """Present if the column is an identity column; ``None`` otherwise."""

    generated_expression: str | None = None
    """SQL expression for a generated stored column (``GENERATED ALWAYS AS``).

    Present if and only if this is a generated stored column.
    """

    @model_validator(mode="after")
    def _check_column_variant_invariants(self) -> Self:
        has_identity = self.identity is not None
        has_generated = self.generated_expression is not None

        if has_identity and has_generated:
            raise ValueError(
                "A column cannot be both an identity column and a generated stored column"
            )

        if has_generated and self.default_expr is not None:
            raise ValueError(
                "A generated stored column must not have a default_expr; "
                "its value is always derived from generated_expression"
            )

        if has_identity and self.default_expr is not None:
            raise ValueError(
                "An identity column must not have a default_expr; "
                "its value is always derived from the identity sequence"
            )

        return self

    @property
    def is_identity(self) -> bool:
        """Return ``True`` if this column uses ``GENERATED … AS IDENTITY``."""
        return self.identity is not None

    @property
    def is_generated_stored(self) -> bool:
        """Return ``True`` if this column is a ``GENERATED ALWAYS AS … STORED`` column."""
        return self.generated_expression is not None
